language: node_js
node_js:
  - '0.10'
before_script:
  - npm install -g grunt-cli
  - ./create_config.sh
env:
  global:
    - secure: vPyvmXsY1qNrhc9AKDZxzS64vmKhTA8V10SQkn0swh/2pHj3SE9CPW+AMthQtpozC35iGmPB2dbb40m4kil9hZ5NpSGPS1VJ89/4Fq6BEyaCxtfCGFt8EBUioawVIMr5WMxLfoOPzE0b+7FQCKFJSK2j2LADJbXXaq4bDQr08oQ=
    - secure: Ugwc9eWMWgxxV1DteXTXkbLhrB1mFjEFBdWaaEpwSg2k9KzJtAJ/oahn5m4C1iVx2xRMICtZvbLIBuGsiR8rYT9KFYZLpTj1Wvpo9Zn0aC3Im1L0C3DHKB3Rp5cEbpiYx1HKePaDExnYR9eMs6UHH4P3TFG9OB76E1C4kaA7mOU=
    - secure: EdzxfUGnJTyI+O9AKHL/ZvyEUXrL8yVaTQzmhLmdDQda+AJiNJm45TjV02sHzu9ZGgSYuggwzP7u8Jm/lHUirBMMDeyf/NtyyxqTe4cIqa/zfCQfobe+LHkhfWuEZ/Sn5dnRHdthiE3UQCvD0wOoKIpYKdL74O1Yq/YkhzQnMxU=
    - secure: t22/ORYIWuGR6a4vpkUwpf5J2e6Fm1N+tD4T7RmxyKph0Ga6PJl35k6fy4URuoeZAKb7Oew7PFtKzTtbwJcnlX8KzJWUhUqpG4NyqYKR/UOq71obB//z1vRfx0jRGPgF+nziohtTFNouG4rjXGjqfWAQVomzP3owqfEuhFKrOGg=
    - secure: kfucP0g6LKK02eFCqFFSSVGgKUBQ6O8fw3rktFoQIQPQX7tkHfqQI3bzmx1CUX+eYlt/cw4wOdSHcoxb2OL/dW8h227mAHoI3nr/8WCyD4LHJu8Ary1fVhdPhJQ0lmSylLUji1rfyqt9kOXNzM8auv7xJIpMbKq9SBDRZenipwo=
    - secure: Tx5nHMuCJ0uwn9HJfZ33SzM7zWJYzbuxajMleeGCbg2oeeLhJsdD4UiIupLuj6sVp7i7QjBTjrTnysN3VrpvXbrmsGcARnJjxRB1nlFHXOVdXzMUh4pMcBTcUIytIoCFHNv59FrsANN83Z5pfMlavrD5JKlpxJtuAoHdCREHC5w=
notifications:
  hipchat:
    rooms:
      - secure: eEG/s3MVwTW5r3IIPJsGql4hBsq/lqCZT5svYrFCsEIO8d3bOqnNQlAEd8WnluUomsvdjWm9plw7wIG0YDzof4ak23OLPMwrBeRpPwFUGimPdBFQDF6sLy/oMRrILbsjmCtILfHlEgTHIkWlA/+iFIEBKnQVDk3NKHwhixKetX0=
    template:
      - '%{repository}#%{build_number} (%{author}): %{message} (<a href="%{build_url}">Details</a> / <a href="%{compare_url}">Compare</a>)'
    format: html
    on_success: change
    on_failure: always
branches:
  only:
    - master
